eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:8766
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        #include: refresh,health,info
        include: '*'