eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8771
spring:
  application:
    name: ribbon-consumer
  zipkin:
    base-url: http://localhost:8766
    sleuth:
      sampler:
        probability: 1.0
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'