eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8773
zuul:
  routes:
    api:
      path: /xum/**
      serviceId: eureka-client
#zuul:
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: microservice-client-ribbon
#    api-b:
#      path: /api-b/**
#      serviceId: microservice-client-feign
spring:
  application:
    name: eureka-zuul
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'