eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
  datasource:
    #schema[0]: classpath:/zipkin.sql
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1332080218
    driver-class-name: com.mysql.cj.jdbc.Driver
    continue-on-error: true
  #rabbitmq:
   # host: 127.0.0.1
   # port: 5672
   # username: guest
   # password: guest
zipkin:
  storage:
    type: mysql
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    web:
      server:
        auto-time-requests: false
